// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuertoBB.Infrastructure.Data;

#nullable disable

namespace PuertoBB.Infrastructure.Migrations.CamaraPortuaria
{
    [DbContext(typeof(CamaraPortuariaDbContext))]
    [Migration("20260608052702_AgregarCondicionIvaEmpresa")]
    partial class AgregarCondicionIvaEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.ConceptoRecibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ConceptosRecibo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipNotaDeCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipRecibo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailRemitente")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmtpSeguridad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoAfipNotaDeCredito = 13,
                            CodigoAfipRecibo = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "",
                            DiasVencimiento = 30,
                            RazonSocial = "",
                            SmtpPort = 587,
                            SmtpSeguridad = 0
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmailEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmailsEmpresa");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicionIva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmpresaGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.HasIndex("EmpresaId", "GrupoFacturacionId")
                        .IsUnique();

                    b.ToTable("EmpresasGrupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReciboOriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReciboOriginalId")
                        .IsUnique();

                    b.ToTable("NotasDeCredito");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificadoKeyRuta")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoRuta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsarHomologacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.ToTable("PuntosDeVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ConfiguracionId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Principal",
                            Numero = 1,
                            UsarHomologacion = false
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvioMail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoPago")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErrorCae")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErrorMail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.HasIndex("EmpresaId", "GrupoFacturacionId", "PeriodoAnio", "PeriodoMes")
                        .IsUnique();

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmailEmpresa", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Emails")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmpresaGrupo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Grupos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", "Grupo")
                        .WithMany("Empresas")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", "ReciboOriginal")
                        .WithOne("NotaDeCredito")
                        .HasForeignKey("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", "ReciboOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReciboOriginal");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.PuntoDeVenta", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", null)
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Recibos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", "Grupo")
                        .WithMany("Recibos")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", b =>
                {
                    b.Navigation("PuntosDeVenta");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Grupos");

                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.Navigation("NotaDeCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
