// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuertoBB.Infrastructure.Data;

#nullable disable

namespace PuertoBB.Infrastructure.Migrations.CamaraPortuaria
{
    [DbContext(typeof(CamaraPortuariaDbContext))]
    partial class CamaraPortuariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.ConceptoRecibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ConceptosRecibo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Autenticacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipNotaDeCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipRecibo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailRemitente")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngresosBrutos")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InicioActividades")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthAuthorizeEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<int>("OAuthFlujo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OAuthProveedor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OAuthRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthTokenEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmtpSeguridad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autenticacion = 1,
                            CodigoAfipNotaDeCredito = 13,
                            CodigoAfipRecibo = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "",
                            DiasVencimiento = 30,
                            OAuthFlujo = 0,
                            OAuthProveedor = 0,
                            RazonSocial = "",
                            SmtpPort = 587,
                            SmtpSeguridad = 0
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmailEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmailsEmpresa");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmisionGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReciboId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReciboId")
                        .IsUnique();

                    b.HasIndex("GrupoFacturacionId", "EmpresaId", "PeriodoAnio", "PeriodoMes")
                        .IsUnique();

                    b.ToTable("EmisionesGrupo", (string)null);
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CondicionIvaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsMoroso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmpresaGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.HasIndex("EmpresaId", "GrupoFacturacionId")
                        .IsUnique();

                    b.ToTable("EmpresasGrupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacionLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.ToTable("GruposLineas");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReciboOriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReciboOriginalId")
                        .IsUnique();

                    b.ToTable("NotasDeCredito");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CertificadoContenido")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CertificadoKeyContenido")
                        .HasColumnType("BLOB");

                    b.Property<string>("CertificadoKeyRuta")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoRuta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsarHomologacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.ToTable("PuntosDeVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ConfiguracionId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Principal",
                            Numero = 1,
                            UsarHomologacion = false
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvioMail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceptorCondicionIva")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceptorCondicionIvaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceptorCuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorDomicilio")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptorRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErrorCae")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErrorMail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PuntoDeVenta", "NumeroComprobante", "CodigoAfip")
                        .IsUnique()
                        .HasFilter("\"NumeroComprobante\" > 0");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.ReciboLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReciboId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReciboId");

                    b.ToTable("RecibosLineas");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmailEmpresa", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Emails")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmisionGrupo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", "Grupo")
                        .WithMany("Emisiones")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", "Recibo")
                        .WithOne("EmisionGrupo")
                        .HasForeignKey("PuertoBB.Core.Entities.CamaraPortuaria.EmisionGrupo", "ReciboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.EmpresaGrupo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Grupos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", "Grupo")
                        .WithMany("Empresas")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacionLinea", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", "Grupo")
                        .WithMany("Lineas")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", "ReciboOriginal")
                        .WithOne("NotaDeCredito")
                        .HasForeignKey("PuertoBB.Core.Entities.CamaraPortuaria.NotaDeCredito", "ReciboOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReciboOriginal");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.PuntoDeVenta", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", null)
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", "Empresa")
                        .WithMany("Recibos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.ReciboLinea", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", "Recibo")
                        .WithMany("Lineas")
                        .HasForeignKey("ReciboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Configuracion", b =>
                {
                    b.Navigation("PuntosDeVenta");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Empresa", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Grupos");

                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.GrupoFacturacion", b =>
                {
                    b.Navigation("Emisiones");

                    b.Navigation("Empresas");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CamaraPortuaria.Recibo", b =>
                {
                    b.Navigation("EmisionGrupo");

                    b.Navigation("Lineas");

                    b.Navigation("NotaDeCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
