// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuertoBB.Infrastructure.Data;

#nullable disable

namespace PuertoBB.Infrastructure.Migrations.CentroMaritimo
{
    [DbContext(typeof(CentroMaritimoDbContext))]
    [Migration("20260608004952_AgregarSmtpSeguridad")]
    partial class AgregarSmtpSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.AgenciaGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.HasIndex("AgenciaId", "GrupoFacturacionId")
                        .IsUnique();

                    b.ToTable("AgenciasGrupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Barco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Barcos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipNotaDeCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfipRecibo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CuitApoderado")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailRemitente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteVoucherPredeterminado")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreApoderado")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmtpSeguridad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsuario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsarApoderado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoAfipNotaDeCredito = 13,
                            CodigoAfipRecibo = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Cuit = "",
                            DiasVencimiento = 30,
                            ImporteVoucherPredeterminado = 0m,
                            RazonSocial = "",
                            SmtpPort = 587,
                            SmtpSeguridad = 0,
                            UsarApoderado = false
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.ContadorVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UltimoNumero = 0
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.EmailAgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("EmailsAgencia");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.GrupoFacturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.NotaDeCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReciboOriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReciboOriginalId")
                        .IsUnique();

                    b.ToTable("NotasDeCredito");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificadoKeyRuta")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoRuta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsarHomologacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.ToTable("PuntosDeVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ConfiguracionId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Principal",
                            Numero = 1,
                            UsarHomologacion = false
                        });
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuitApoderado")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsApoderado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsConsolidadoVouchers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoCAE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimientoPago")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupoFacturacionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreApoderado")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFacturacionId");

                    b.HasIndex("AgenciaId", "PeriodoAnio", "PeriodoMes")
                        .IsUnique()
                        .HasFilter("\"EsConsolidadoVouchers\" = 1");

                    b.HasIndex("AgenciaId", "GrupoFacturacionId", "PeriodoAnio", "PeriodoMes")
                        .IsUnique();

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarcoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReciboId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("BarcoId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ReciboId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.AgenciaGrupo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Agencia", "Agencia")
                        .WithMany("Grupos")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.GrupoFacturacion", "Grupo")
                        .WithMany("Agencias")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.EmailAgencia", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Agencia", "Agencia")
                        .WithMany("Emails")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.NotaDeCredito", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Recibo", "ReciboOriginal")
                        .WithOne("NotaDeCredito")
                        .HasForeignKey("PuertoBB.Core.Entities.CentroMaritimo.NotaDeCredito", "ReciboOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReciboOriginal");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.PuntoDeVenta", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Configuracion", null)
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Recibo", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Agencia", "Agencia")
                        .WithMany("Recibos")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.GrupoFacturacion", "Grupo")
                        .WithMany("Recibos")
                        .HasForeignKey("GrupoFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agencia");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Voucher", b =>
                {
                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Agencia", "Agencia")
                        .WithMany("Vouchers")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Barco", "Barco")
                        .WithMany()
                        .HasForeignKey("BarcoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuertoBB.Core.Entities.CentroMaritimo.Recibo", "Recibo")
                        .WithMany("Vouchers")
                        .HasForeignKey("ReciboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agencia");

                    b.Navigation("Barco");

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Agencia", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Grupos");

                    b.Navigation("Recibos");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Configuracion", b =>
                {
                    b.Navigation("PuntosDeVenta");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.GrupoFacturacion", b =>
                {
                    b.Navigation("Agencias");

                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("PuertoBB.Core.Entities.CentroMaritimo.Recibo", b =>
                {
                    b.Navigation("NotaDeCredito");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
